#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_TIME=$(echo "${BATTERY_INFO}" | awk '/^Battery/ {print($5)}')

URGENT_VALUE=15


if [[ "${BATTERY_STATE}" = "Charging" ]]; then
	if [ "${BATTERY_POWER}" -ge "80" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} ⚡"
	elif [ "${BATTERY_POWER}" -lt "80" ] && [ "${BATTERY_POWER}" -ge "60" ]; then
	  	echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} ⚡"
	elif [ "${BATTERY_POWER}" -lt "60" ] && [ "${BATTERY_POWER}" -ge "40" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} ⚡"
	elif [ "${BATTERY_POWER}" -lt "40" ] && [ "${BATTERY_POWER}" -ge "20" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} ⚡"
	elif [ "${BATTERY_POWER}" -lt "20" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} ⚡"

	fi	
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
	if [ "${BATTERY_POWER}" -ge "80" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} Remaining"
	elif [ "${BATTERY_POWER}" -lt "80" ] && [ "${BATTERY_POWER}" -ge "60" ]; then
	  	echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} Remaining"
	elif [ "${BATTERY_POWER}" -lt "60" ] && [ "${BATTERY_POWER}" -ge "40" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} Remaining"
	elif [ "${BATTERY_POWER}" -lt "40" ] && [ "${BATTERY_POWER}" -ge "20" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} Remaining"
	elif [ "${BATTERY_POWER}" -lt "20" ]; then
		echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} Remaining"
s
	fi
else
	echo "  ${BATTERY_POWER}%  ${BATTERY_TIME} ⚡"
  	echo "${BATTERY_POWER}%"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
