#!/home/panas/anaconda3/bin/python

import subprocess

volume_info = subprocess.run(
    ["amixer", "sget", "Master"], stdout=subprocess.PIPE, text=True).stdout
volume_status = 'on' if volume_info[-3] == 'n' else "off"
volume_value = int(subprocess.run(
    ["pamixer", "--get-volume"], stdout=subprocess.PIPE).stdout.decode('utf-8'))

if volume_status == 'off':
    print("Mute")
    print('Mute')
    print("#FFFC00")

else:
    print(f"{volume_value}%")
    print(f"{volume_value}%")

    if volume_value > 100:
        print("#FFFC00")
