#!/bin/sh

sink=0
volume=$(pactl list sinks | perl -slne '
   if (/^Sink #(\d+)$/) {
       $cur_sink = $1;
   } elsif (/^\s+Volume:.*? (\d+)% / && $sink eq $cur_sink)     {
       print $1;
   }
' -- -sink="$sink")

pactl set-sink-volume 0 -5%

